### ISSUE TITLE
Implement Business Fields

### ISSUE THREAD

**Issue by paulperrone** [OakdaleInnovation/oi-beacon-request#12]
The default business form field shall be a single field. When text is typed into it the field will reference the Places API and begin suggesting businesses. If the user is registered within the Places API, then they should be able to select their business and have its information fill the form.

The backup field should not be visible by default. It should consist of Address, City, State, and Zip Code fields.

Near the field there should be some element that can toggle between the default and the backup business field. When clicked, the backup field should replace the default field if the default field is showing, or the reverse if the secondary field is showing.

**Comment by Reshurum** [comment]
Resolved in #19.
