### ISSUE TITLE
<form is=""> deprecated in CE v1 spec

### ISSUE THREAD

**Issue by justinribeiro** [OakdaleInnovation/oi-beacon-request#14]
The current form implementation utilizes `<form is="">` as part of `iron-form` 1.1.5. This won't work as intended in Polymer 2. Instead:

1. Switch to `2.0-preview` branch for `iron-form`.
2. Switch to `iron-form` wrapping `form` as per 2.0 element specification.
3. Bind the submit via `iron-form-presubmit` handler in the `connect` lifecycle.

**Comment by Reshurum** [comment]
Resolved in #17.
