### ISSUE TITLE
Create basic form layout with paper elements

### ISSUE THREAD

**Issue by Reshurum** [OakdaleInnovation/oi-beacon-request#2]
The form at the very least must consist of a header, business name, business address, website fields, and a submit button.

**Comment by paulperrone** [comment]
Here is a design of the form from Laura for consideration. We're not looking for an exact match, but this is a solid signpost for your progress.

![beacon info page 1](https://user-images.githubusercontent.com/6682933/27191490-c2b3ff8e-51ac-11e7-9444-d5e98b129e78.jpg)
